/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package view.page;

import java.awt.Frame;
import java.util.HashMap;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JDialog;
import javax.swing.JOptionPane;
import static javax.swing.JOptionPane.WARNING_MESSAGE;
import javax.swing.SwingUtilities;
import payloads.UserPermission;
import socket.StatusCode;
import socket.socketManager;
import view.page.ShareOptionPane;

/**
 *
 * @author Son
 */
public class folderPermission extends javax.swing.JPanel{
    private String filename,username;

    /**
     * Creates new form NewJPanel
     * @param userPermission
     * @param filename
     */
    public folderPermission(UserPermission userPermission,String filename) {
        initComponents();
        this.filename= filename;
        username = userPermission.getUserData().getUsername();
        String fullname = userPermission.getUserData().getLastName() + " "+userPermission.getUserData().getFirstName();
        HashMap<String,Object> permission = userPermission.getProcessedPermission();
        boolean uploadable =(boolean) permission.get("uploadable");
        boolean downloadable = (boolean)permission.get("downloadable");
        boolean canModify = (boolean)permission.get("canModify");
        fullnameLbl.setText(fullname);
        usernameLbl.setText(username);
        downCb.setSelected(downloadable);
        upCb.setSelected(uploadable);
        modifyCb.setSelected(canModify);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        fullnameLbl = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        usernameLbl = new javax.swing.JLabel();
        downCb = new view.custom.checkBox();
        upCb = new view.custom.checkBox();
        modifyCb = new view.custom.checkBox();
        renameConfirm2 = new view.custom.Button();

        setBackground(new java.awt.Color(255, 255, 255));
        setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(204, 204, 204)));

        fullnameLbl.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        fullnameLbl.setText("<Name>");

        jLabel2.setFont(new java.awt.Font("Verdana", 1, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 0, 0));
        jLabel2.setText("X");
        jLabel2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel2MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jLabel2MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jLabel2MouseExited(evt);
            }
        });

        usernameLbl.setText("<username>");

        downCb.setBackground(new java.awt.Color(153, 153, 255));
        downCb.setText("Download");
        downCb.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                downCbActionPerformed(evt);
            }
        });

        upCb.setBackground(new java.awt.Color(153, 153, 255));
        upCb.setText("Upload");
        upCb.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                upCbActionPerformed(evt);
            }
        });

        modifyCb.setBackground(new java.awt.Color(153, 153, 255));
        modifyCb.setText("Chỉnh sửa");
        modifyCb.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                modifyCbActionPerformed(evt);
            }
        });

        renameConfirm2.setText("Thêm");
        renameConfirm2.setColor(new java.awt.Color(204, 204, 204));
        renameConfirm2.setColorClick(new java.awt.Color(153, 153, 153));
        renameConfirm2.setColorOver(new java.awt.Color(102, 102, 102));
        renameConfirm2.setRadius(10);
        renameConfirm2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                renameConfirm2ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(renameConfirm2, javax.swing.GroupLayout.PREFERRED_SIZE, 94, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(fullnameLbl, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(usernameLbl))
                        .addGap(18, 18, Short.MAX_VALUE)
                        .addComponent(downCb, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(21, 21, 21)
                        .addComponent(upCb, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(modifyCb, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel2)
                .addGap(20, 20, 20))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(fullnameLbl, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(usernameLbl))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(22, 22, 22)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(downCb, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(upCb, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(modifyCb, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel2))
                        .addGap(18, 18, 18)
                        .addComponent(renameConfirm2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(20, 20, 20))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void jLabel2MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel2MouseEntered
        jLabel2.setForeground(new java.awt.Color(255,153,153));
    }//GEN-LAST:event_jLabel2MouseEntered

    private void jLabel2MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel2MouseExited
        jLabel2.setForeground(new java.awt.Color(255, 0, 0));
    }//GEN-LAST:event_jLabel2MouseExited

    private void jLabel2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel2MouseClicked
        jLabel2.setForeground(new java.awt.Color(255,51,51));
        try {
            ShareOptionPane parentFrame = (ShareOptionPane) SwingUtilities.getWindowAncestor(this);
            if(socketManager.getInstance().deletePermission("directory", filename, username).getStatus() == StatusCode.FILE_ACTION_NOT_TAKEN){
                JOptionPane.showMessageDialog(parentFrame, "Có lỗi xảy ra, tiến hành cập nhật lại danh sách!", "Thông báo", WARNING_MESSAGE);
            }
            parentFrame.refreshContent();
        } catch (Exception ex) {
            Logger.getLogger(folderPermission.class.getName()).log(Level.SEVERE, null, ex);
        }
        
        
    }//GEN-LAST:event_jLabel2MouseClicked

    private void downCbActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_downCbActionPerformed

    }//GEN-LAST:event_downCbActionPerformed

    private void upCbActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_upCbActionPerformed

    }//GEN-LAST:event_upCbActionPerformed

    private void modifyCbActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_modifyCbActionPerformed

    }//GEN-LAST:event_modifyCbActionPerformed

    private void renameConfirm2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_renameConfirm2ActionPerformed
        try {
            changePermission();
        } catch (Exception ex) {
            Logger.getLogger(folderPermission.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_renameConfirm2ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private view.custom.checkBox downCb;
    private javax.swing.JLabel fullnameLbl;
    private javax.swing.JLabel jLabel2;
    private view.custom.checkBox modifyCb;
    private view.custom.Button renameConfirm2;
    private view.custom.checkBox upCb;
    private javax.swing.JLabel usernameLbl;
    // End of variables declaration//GEN-END:variables


    public void changePermission() throws Exception {
        String sql="directory "+filename+" "+username+
                " "+(modifyCb.isSelected()?"true":"false")+
                " "+(upCb.isSelected()?"true":"false")+
                " "+(downCb.isSelected()?"true":"false")
                ;
        System.out.println(sql);
        socket.socketManager.getInstance().grantFolderPermission(filename, username, modifyCb.isSelected(),upCb.isSelected(), downCb.isSelected() );
    }
}
