/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package view.page;

import java.awt.Frame;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import java.io.IOException;
import java.text.SimpleDateFormat;
import java.util.Date;
import java.util.regex.Pattern;
import javax.swing.JFrame;
import static javax.swing.JOptionPane.INFORMATION_MESSAGE;
import static javax.swing.JOptionPane.WARNING_MESSAGE;
import javax.swing.SwingUtilities;
import payloads.StringResponse;
import socket.socketManager;
import view.custom.customDialog;
import socket.StatusCode;


/**
 *
 * @author Bum
 */
public final class register extends javax.swing.JPanel {
    private customDialog customDialog;
    private Frame parentFrame;
    String username=null,password=null;

    /**
     * Creates new form register
     */
    public register() {
        initComponents();
        createCustomdialog();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        otpVerifyPanel = new javax.swing.JPanel();
        verifyConfirm = new view.custom.Button();
        verifyCancel = new view.custom.Button();
        verifyTitle = new javax.swing.JLabel();
        verifyField = new view.custom.textField();
        regenerateBtn = new view.custom.Button();
        genderSelection = new javax.swing.ButtonGroup();
        jPanel1 = new javax.swing.JPanel();
        firstnameField = new view.custom.textField();
        verifyPasswordField = new view.custom.passwordField();
        passwordField = new view.custom.passwordField();
        usernameField = new view.custom.textField();
        birthdayField = new de.wannawork.jcalendar.JCalendarComboBox();
        jLabel1 = new javax.swing.JLabel();
        regBtn = new view.custom.Button();
        lastnameField = new view.custom.textField();
        male = new javax.swing.JRadioButton();
        female = new javax.swing.JRadioButton();

        otpVerifyPanel.setBackground(new java.awt.Color(255, 255, 255));
        otpVerifyPanel.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(216, 216, 216)));

        verifyConfirm.setText("Xác nhận");
        verifyConfirm.setColor(new java.awt.Color(204, 204, 255));
        verifyConfirm.setColorClick(new java.awt.Color(153, 153, 153));
        verifyConfirm.setColorOver(new java.awt.Color(102, 102, 102));
        verifyConfirm.setRadius(10);
        verifyConfirm.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                verifyConfirmActionPerformed(evt);
            }
        });

        verifyCancel.setText("Hủy");
        verifyCancel.setColor(new java.awt.Color(204, 204, 255));
        verifyCancel.setColorClick(new java.awt.Color(153, 153, 153));
        verifyCancel.setColorOver(new java.awt.Color(102, 102, 102));
        verifyCancel.setRadius(10);
        verifyCancel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                verifyCancelActionPerformed(evt);
            }
        });

        verifyTitle.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        verifyTitle.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        verifyTitle.setText("Xác thực OTP");

        verifyField.setLabelText("OTP");

        regenerateBtn.setText("Gửi lại mã");
        regenerateBtn.setColor(new java.awt.Color(204, 204, 204));
        regenerateBtn.setColorClick(new java.awt.Color(153, 153, 153));
        regenerateBtn.setColorOver(new java.awt.Color(102, 102, 102));
        regenerateBtn.setRadius(5);
        regenerateBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                regenerateBtnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout otpVerifyPanelLayout = new javax.swing.GroupLayout(otpVerifyPanel);
        otpVerifyPanel.setLayout(otpVerifyPanelLayout);
        otpVerifyPanelLayout.setHorizontalGroup(
            otpVerifyPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(otpVerifyPanelLayout.createSequentialGroup()
                .addGap(94, 94, 94)
                .addGroup(otpVerifyPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(verifyTitle, javax.swing.GroupLayout.PREFERRED_SIZE, 300, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(otpVerifyPanelLayout.createSequentialGroup()
                        .addComponent(verifyConfirm, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(verifyCancel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(otpVerifyPanelLayout.createSequentialGroup()
                        .addComponent(verifyField, javax.swing.GroupLayout.PREFERRED_SIZE, 220, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(regenerateBtn, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(110, Short.MAX_VALUE))
        );
        otpVerifyPanelLayout.setVerticalGroup(
            otpVerifyPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(otpVerifyPanelLayout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addGroup(otpVerifyPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(otpVerifyPanelLayout.createSequentialGroup()
                        .addComponent(verifyTitle)
                        .addGap(27, 27, 27)
                        .addComponent(verifyField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(regenerateBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(34, 34, 34)
                .addGroup(otpVerifyPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(verifyCancel, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(verifyConfirm, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(49, Short.MAX_VALUE))
        );

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setMinimumSize(new java.awt.Dimension(100, 378));
        jPanel1.setPreferredSize(new java.awt.Dimension(400, 400));
        jPanel1.setRequestFocusEnabled(false);

        firstnameField.setLabelText("Họ");

        verifyPasswordField.setLabelText("Xác nhận mật khẩu");

        passwordField.setLabelText("Mật khẩu");
        passwordField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                passwordFieldActionPerformed(evt);
            }
        });

        usernameField.setLabelText("email");

        jLabel1.setForeground(new java.awt.Color(153, 153, 153));
        jLabel1.setText("Ngày sinh");

        regBtn.setBackground(new java.awt.Color(204, 204, 255));
        regBtn.setText("Đăng kí");
        regBtn.setColor(new java.awt.Color(204, 204, 255));
        regBtn.setColorOver(new java.awt.Color(255, 204, 204));
        regBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                regBtnActionPerformed(evt);
            }
        });

        lastnameField.setLabelText("Tên");

        genderSelection.add(male);
        male.setText("Nam");

        genderSelection.add(female);
        female.setText("Nữ");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(85, 85, 85)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(regBtn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(usernameField, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(passwordField, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(verifyPasswordField, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(firstnameField, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(lastnameField, javax.swing.GroupLayout.PREFERRED_SIZE, 156, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel1)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(birthdayField, javax.swing.GroupLayout.PREFERRED_SIZE, 171, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(5, 5, 5)
                                .addComponent(male)
                                .addGap(18, 18, 18)
                                .addComponent(female)))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap(80, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(usernameField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(firstnameField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lastnameField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(male)
                    .addComponent(female))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1)
                    .addComponent(birthdayField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(passwordField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(verifyPasswordField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(regBtn, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(60, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void passwordFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_passwordFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_passwordFieldActionPerformed

    private void regBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_regBtnActionPerformed
        if(checkInputField()){
            SimpleDateFormat dateFormat = new SimpleDateFormat("dd/MM/yyyy");
            String birthday = dateFormat.format(birthdayField.getDate());
            username = usernameField.getText();password = passwordField.getText();
            String gender = male.isSelected()?"Nam":"Nữ";
            String firstname = firstnameField.getText();
            String lastname = lastnameField.getText();
            String data=String.format("{\n"
                + "            \"username\": \"%s\",\n"
                + "            \"password\": \"%s\";\n"
                + "            \"firstName\": \"%s\",\n"
                + "            \"lastName\": \"%s\",\n"
                + "            \"gender\": \"%s\",\n"
                + "            \"birthday\": \"%s\"\n"
                + "        }",username,password,firstname,lastname,gender,birthday);
            try {
                StringResponse response =socketManager.getInstance().register(data);
                if(response.getStatus() == StatusCode.CLOSING_DATA_CONNECTION){
                    JOptionPane.showMessageDialog(parentFrame, "Đăng ký thành công, hãy kiểm tra email để xác thực otp", "Success!!", INFORMATION_MESSAGE);
                    customDialog.setVisible(true);
                }else{
                    JOptionPane.showMessageDialog(this,"username đã tồn tại!! ","Thông báo",WARNING_MESSAGE);
                }
            } catch (Exception ex) {
                Logger.getLogger(register.class.getName()).log(Level.SEVERE, null, ex);
            }
        }
    }//GEN-LAST:event_regBtnActionPerformed

    private void verifyConfirmActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_verifyConfirmActionPerformed
        String otp = verifyField.getText();
        if(!otp.isEmpty()){
            try {
                StringResponse response = socketManager.getInstance().verifyOTP(username, password, otp);
                if(response.getStatus() == StatusCode.COMMAND_OK){
                    JOptionPane.showMessageDialog(parentFrame, "Xác thực thành công!! Vui lòng đăng nhập lại","Success",INFORMATION_MESSAGE);
                    customDialog.setVisible(false);
                    reLogin();
                }else{
                    JOptionPane.showMessageDialog(this, "OTP không đúng hoặc đã hết hạn!!","Thông báo",WARNING_MESSAGE);
                }
            } catch (Exception ex) {
                Logger.getLogger(login.class.getName()).log(Level.SEVERE, null, ex);
            }
        }
    }//GEN-LAST:event_verifyConfirmActionPerformed

    private void verifyCancelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_verifyCancelActionPerformed
        customDialog.setVisible(false);
        verifyField.setText("");
        JOptionPane.showMessageDialog(this,"Tài khoản đăng ký thành công, Vui lòng xác thực OTP ở lần đăng nhập kế tiếp","Thông báo",WARNING_MESSAGE);
        reLogin();
    }//GEN-LAST:event_verifyCancelActionPerformed

    private void regenerateBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_regenerateBtnActionPerformed
        try {
            StringResponse res = socketManager.getInstance().regenerateOTP(username, password);
            if(res.getStatus()==StatusCode.COMMAND_OK){
                JOptionPane.showMessageDialog(parentFrame, "Đã gửi lại mã OTP, vui lòng check mail","Success",INFORMATION_MESSAGE);
            }
            else
                JOptionPane.showMessageDialog(parentFrame, "Có lỗi xảy ra, vui lòng thử lại","Thông báo",WARNING_MESSAGE);
        } catch (Exception ex) {
            Logger.getLogger(register.class.getName()).log(Level.SEVERE, null, ex);
        }
        
    }//GEN-LAST:event_regenerateBtnActionPerformed
    public void createCustomdialog(){
        parentFrame = (Frame) SwingUtilities.getWindowAncestor(this);
        customDialog = new customDialog(parentFrame);
        customDialog.setDialogContent(otpVerifyPanel);
    }
    
    public boolean checkInputField(){
        String checkPassword = passwordField.getText();
        
        if(usernameField.getText().isEmpty()||checkPassword.isEmpty()||firstnameField.getText().isEmpty()||lastnameField.getText().isEmpty()||genderSelection.getSelection()==null){
            JOptionPane.showMessageDialog(this,"Vui lòng không để trống thông tin","Thông báo",WARNING_MESSAGE);
            return false;
        }
        Pattern EMAIL_PATTERN = Pattern.compile("^[a-zA-Z0-9._%+-]+@[a-zA-Z0-9.-]+\\.[a-zA-Z]{2,}$");
        if(!EMAIL_PATTERN.matcher(usernameField.getText()).matches()){
            JOptionPane.showMessageDialog(this,"Vui lòng nhập đúng định dạng email!!","Thông báo",WARNING_MESSAGE);
            return false;
        }
        Date date = birthdayField.getDate();
        if(date.after(new Date())){
            JOptionPane.showMessageDialog(this,"Vui lòng nhập ngày tháng năm sinh chính xác!!","Thông báo",WARNING_MESSAGE);
            return false;
        }   
        if(checkPassword.length()<4){
            JOptionPane.showMessageDialog(this,"Mật khẩu tối thiểu 4 ký tự!!","Thông báo",WARNING_MESSAGE);
            return false;
        }
        if(!checkPassword.equals(verifyPasswordField.getText())){
            JOptionPane.showMessageDialog(this,"Mật khẩu không khớp!!","Thông báo",WARNING_MESSAGE);
            return false;
        }
        return true;
    }
    
    public void reLogin(){
        JFrame frame = (JFrame) SwingUtilities.getWindowAncestor(this);
        frame.dispose();
        new loginForm().setVisible(true);
    }
        
        

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private de.wannawork.jcalendar.JCalendarComboBox birthdayField;
    private javax.swing.JRadioButton female;
    private view.custom.textField firstnameField;
    private javax.swing.ButtonGroup genderSelection;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private view.custom.textField lastnameField;
    private javax.swing.JRadioButton male;
    private javax.swing.JPanel otpVerifyPanel;
    private view.custom.passwordField passwordField;
    private view.custom.Button regBtn;
    private view.custom.Button regenerateBtn;
    private view.custom.textField usernameField;
    private view.custom.Button verifyCancel;
    private view.custom.Button verifyConfirm;
    private view.custom.textField verifyField;
    private view.custom.passwordField verifyPasswordField;
    private javax.swing.JLabel verifyTitle;
    // End of variables declaration//GEN-END:variables
}
