/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JDialog.java to edit this template
 */
package view.page;

import java.awt.Dialog;
import java.awt.Dimension;
import java.awt.Frame;
import java.util.List;
import javax.swing.BoxLayout;
import javax.swing.JOptionPane;
import static javax.swing.JOptionPane.WARNING_MESSAGE;
import payloads.UserPermission;
import payloads.UserPermissionResponse;
import socket.StatusCode;
import socket.socketManager;

/**
 *
 * @author Son
 */
public class ShareOptionPane extends javax.swing.JDialog {
    String type,filename,username;
    Frame parent;
    /**
     * Creates new form NewJDialog
     */
    public ShareOptionPane(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
    }
    public ShareOptionPane(java.awt.Frame parent,String type,String filename) throws Exception{
        super(parent, Dialog.ModalityType.APPLICATION_MODAL);
        initComponents();
        this.parent = parent;
        this.type = type; this.filename = filename;
        username = socketManager.getInstance().getUserInfo().getUsername();
        setContent(type, filename);
        setLocationRelativeTo(null);
    }
    
    public void refreshContent() throws Exception{
        setContent(type, filename);
    }
    
    public void setContent(String type,String shareFileName) throws Exception{
        UserPermissionResponse res = socketManager.getInstance().getShareUserList(shareFileName);
        if(res.getStatus() == StatusCode.ABOUT_TO_OPEN_DATA_CONNECTION){
            List<UserPermission> userList = res.getList();
            shareUserContent.removeAll();
            shareUserContent.revalidate();
            shareUserContent.repaint();
            shareUserContent.setLayout(new BoxLayout(shareUserContent,BoxLayout.Y_AXIS));
            if(type.equals("dir"))
                for(UserPermission user : userList){
                    if(user.getUserData().getUsername().equals(username))
                        continue;
                    folderPermission panel = new folderPermission(user,shareFileName);
                    panel.setPreferredSize(new Dimension(450,100));
                    shareUserContent.add(panel);
                }
            else
                for(UserPermission user : userList){
                    if(user.getUserData().getUsername().equals(username))
                        continue;
                    filePermission panel = new filePermission(user,shareFileName);
                    panel.setPreferredSize(new Dimension(450,100));
                    shareUserContent.add(panel);
                }
        }else {
            JOptionPane.showMessageDialog(parent,"Có lỗi xảy ra, tập tin có thể đã bị đổi tên. Vui lòng thử lại!!","Thông báo",WARNING_MESSAGE);
            this.dispose();
        }
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        sharePanel = new javax.swing.JPanel();
        nameField = new view.custom.textField();
        renameConfirm2 = new view.custom.Button();
        renameConfirm3 = new view.custom.Button();
        roundPanel2 = new view.custom.RoundPanel();
        access5 = new javax.swing.JScrollPane();
        shareUserContent = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setUndecorated(true);

        sharePanel.setBackground(new java.awt.Color(255, 255, 255));
        sharePanel.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(204, 204, 204)));

        nameField.setLabelText("Nhập tên user");

        renameConfirm2.setText("Thêm");
        renameConfirm2.setColor(new java.awt.Color(204, 204, 255));
        renameConfirm2.setColorClick(new java.awt.Color(153, 153, 153));
        renameConfirm2.setColorOver(new java.awt.Color(102, 102, 102));
        renameConfirm2.setRadius(10);
        renameConfirm2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                renameConfirm2ActionPerformed(evt);
            }
        });

        renameConfirm3.setBackground(new java.awt.Color(255, 255, 255));
        renameConfirm3.setText("X");
        renameConfirm3.setColor(new java.awt.Color(255, 255, 255));
        renameConfirm3.setColorClick(new java.awt.Color(153, 153, 153));
        renameConfirm3.setColorOver(new java.awt.Color(102, 102, 102));
        renameConfirm3.setRadius(10);
        renameConfirm3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                renameConfirm3ActionPerformed(evt);
            }
        });

        access5.setBackground(new java.awt.Color(255, 255, 255));

        javax.swing.GroupLayout shareUserContentLayout = new javax.swing.GroupLayout(shareUserContent);
        shareUserContent.setLayout(shareUserContentLayout);
        shareUserContentLayout.setHorizontalGroup(
            shareUserContentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 570, Short.MAX_VALUE)
        );
        shareUserContentLayout.setVerticalGroup(
            shareUserContentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 262, Short.MAX_VALUE)
        );

        access5.setViewportView(shareUserContent);

        javax.swing.GroupLayout roundPanel2Layout = new javax.swing.GroupLayout(roundPanel2);
        roundPanel2.setLayout(roundPanel2Layout);
        roundPanel2Layout.setHorizontalGroup(
            roundPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(roundPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(access5, javax.swing.GroupLayout.DEFAULT_SIZE, 494, Short.MAX_VALUE)
                .addContainerGap())
        );
        roundPanel2Layout.setVerticalGroup(
            roundPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(roundPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(access5, javax.swing.GroupLayout.PREFERRED_SIZE, 264, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel1.setText("Danh sách người dùng được chia sẻ");

        javax.swing.GroupLayout sharePanelLayout = new javax.swing.GroupLayout(sharePanel);
        sharePanel.setLayout(sharePanelLayout);
        sharePanelLayout.setHorizontalGroup(
            sharePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(sharePanelLayout.createSequentialGroup()
                .addContainerGap(42, Short.MAX_VALUE)
                .addGroup(sharePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, sharePanelLayout.createSequentialGroup()
                        .addGroup(sharePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(roundPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(sharePanelLayout.createSequentialGroup()
                                .addGroup(sharePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jLabel1)
                                    .addComponent(nameField, javax.swing.GroupLayout.PREFERRED_SIZE, 400, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(renameConfirm2, javax.swing.GroupLayout.PREFERRED_SIZE, 94, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(50, 50, 50))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, sharePanelLayout.createSequentialGroup()
                        .addComponent(renameConfirm3, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap())))
        );
        sharePanelLayout.setVerticalGroup(
            sharePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(sharePanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(sharePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(renameConfirm3, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(sharePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(nameField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(renameConfirm2, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(roundPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(46, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(sharePanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(sharePanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void renameConfirm2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_renameConfirm2ActionPerformed
        String name = nameField.getText();
        if(name.isBlank())
            return;
        try{
        if(type.equals("dir")){
            if(socketManager.getInstance().grantFolderPermission(filename, name, false, false, false).getStatus()==StatusCode.FILE_ACTION_NOT_TAKEN){
                JOptionPane.showMessageDialog(parent, "Có vấn đề xảy ra, Không tìm thấy người dùng");
            } else JOptionPane.showMessageDialog(parent, "Thành công");
        }
        else {
            if(socketManager.getInstance().grantFilePermission(filename, name, "r").getStatus()==StatusCode.FILE_ACTION_NOT_TAKEN){
                JOptionPane.showMessageDialog(parent, "có lỗi xảy ra, Không tìm thấy người dùng");
            }else JOptionPane.showMessageDialog(parent, "Thành công");
        }
        refreshContent();
        }catch (Exception e){
            JOptionPane.showMessageDialog(parent, "Có lỗi xảy ra");
        }
    }//GEN-LAST:event_renameConfirm2ActionPerformed

    private void renameConfirm3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_renameConfirm3ActionPerformed
        this.dispose();
    }//GEN-LAST:event_renameConfirm3ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ShareOptionPane.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ShareOptionPane.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ShareOptionPane.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ShareOptionPane.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                ShareOptionPane dialog = new ShareOptionPane(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JScrollPane access5;
    private javax.swing.JLabel jLabel1;
    private view.custom.textField nameField;
    private view.custom.Button renameConfirm2;
    private view.custom.Button renameConfirm3;
    private view.custom.RoundPanel roundPanel2;
    private javax.swing.JPanel sharePanel;
    private javax.swing.JPanel shareUserContent;
    // End of variables declaration//GEN-END:variables
}
