package view.custom;

import java.awt.Color;
import java.awt.Dimension;
import java.awt.Image;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import javax.swing.ImageIcon;
import javax.swing.JPanel;
import javax.swing.JSeparator;

/**
 *
 * @author RAVEN
 */
public class PanelAction extends javax.swing.JPanel {

    customMenuItem option;

    /**
     * Creates new form PanelAction
     */
    public PanelAction() {
        initComponents();
        initOpionMenu();

    }

    public void initOpionMenu() { // Thay đổi đường dẫn tới hình ảnh của bạn
        // Thay đổi đường dẫn tới hình ảnh của bạn
        option = new customMenuItem("<html><b>Gán quyền</b></html>", new ImageIcon(getClass().getResource("/view/img/key.png")));
        optionMenu.add(option);


    }

    public void initEvent(TableActionEvent event, int row) {
        option.addActionListener(new ActionListener() {
            @Override
            public void actionPerformed(ActionEvent ae) {
                event.grantPermission(row);
            }
        });
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        optionMenu = new view.custom.CustomPopupMenu();
        editBtn = new view.custom.ActionButton();

        optionMenu.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(216, 216, 216)));
        optionMenu.setBackgroundColor(java.awt.Color.white);

        editBtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/view/img/dots.png"))); // NOI18N
        editBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                editBtnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(48, 48, 48)
                .addComponent(editBtn, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(52, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(editBtn, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 57, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents

    private void editBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_editBtnActionPerformed
        optionMenu.show(editBtn, editBtn.getX() - 150, editBtn.getY());
    }//GEN-LAST:event_editBtnActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private view.custom.ActionButton editBtn;
    private view.custom.CustomPopupMenu optionMenu;
    // End of variables declaration//GEN-END:variables
}
